#!/usr/bin/env python2

# imagedex: https://github.com/jzacsh/imagedex

import os
import sys
from optparse import OptionParser
import simplejson as json
import io

def usage():
    usage = """
    Usage: %s PATH
        Generate JSON representation of the given directory, PATH.
    """ % (sys.argv[0])
    sys.stderr.write('%s\n' % usage)

def main():
    parser = OptionParser()
    parser.add_option('-f', '--file', dest='outf',
        help="File you'd like your JSON index written to.")
    (opts, args) = parser.parse_args()

    #sanity check
    if len(args) != 1 or not os.path.isdir(args[0]):
        usage()
        sys.exit(1)

    #get an actual index of requested path
    origindex = os.listdir(args[0])
    index = [ args[0] + '/' + path for path in origindex ]

    #finally output data as JSON
    if opts.outf:
      if os.path.isfile(opts.outf) and not os.access(opts.outf, os.W_OK):
        error = 'File "%s" already exists and is not writeable.' % (opts.outf)
        sys.stderr.write('%s\n' % error)
        sys.exit(2)

      f = io.FileIO(opts.outf, 'w')
      f.write(json.dumps(index))
    else:
      print json.dumps(index)

if __name__ == '__main__':
    main()

# vim: et:ts=4:sw=4
