#!/usr/bin/env python2.6

# imagedex: https://github.com/jzacsh/imagedex

import os
import sys
import simplejson as json

def usage():
    usage = """
    Usage: %s PATH
        Generate JSON representation of the given directory, PATH.
    """ % (sys.argv[0])
    sys.stderr.write('%s\n' % usage)

def main():
    if len(sys.argv) != 2 or not os.path.isdir(sys.argv[1]):
        usage()
        sys.exit(1)

    #get an actual index of requested path
    origindex = os.listdir(sys.argv[1])

    #@TODO: why can't i modify origindex in place?
    index = [ sys.argv[1] + '/' + path for path in origindex ]

    #finally output data as JSON
    print json.dumps(index)

if __name__ == '__main__':
    main()

# vim: et:ts=4:sw=4
